name: GitHub Garden

on:
  schedule:
    - cron: "0 0 * * *"   # ÙŠØªØ­Ø¯Ù‘Ø« ÙŠÙˆÙ…ÙŠÙ‹Ø§
  workflow_dispatch:

jobs:
  garden:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          user: Raghad-Moqady
          template: classic
          base: header, activity, community

          # ðŸŒ± Ø§Ù„Ø­Ø¯ÙŠÙ‚Ø©
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_streak: yes
          plugin_streak_days: 365

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_limit: 6

          # Ø´ÙƒÙ„ Ù‡Ø§Ø¯ÙŠ ÙˆØ·Ø¨ÙŠØ¹ÙŠ
          config_timezone: Asia/Jerusalem
